name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - uses: ramsey/composer-install@v3

      - run: composer phpstan

  tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4

      - name: Setup GOST engine
        run: |
          sudo apt install libengine-gost-openssl1.1
          sudo cp tests/openssl.cnf /usr/lib/ssl/openssl.cnf

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run test suite
        run: composer test
